CREATE TABLE ESTATUS (
	EST_CODIGO SERIAL,
	EST_NOMBRE VARCHAR (25) NOT NULL,
	CONSTRAINT PK_CODIGO_ESTATUS PRIMARY KEY (EST_CODIGO)
);

CREATE TABLE HORARIO (
	HOR_CODIGO SERIAL,
	HOR_DIA VARCHAR (10) NOT NULL,
	HOR_HORAINICIO DATE NOT NULL,
	HOR_HORAFIN DATE NOT NULL
	CONSTRAINT CHECK_DIA_HORARIO CHECK(HOR_DIA IN ('LUNES','MARTES','MIERCOLES','JUEVES','VIERNES')),
	CONSTRAINT PK_CODIGO_HORARIO PRIMARY KEY (HOR_CODIGO)
);

CREATE TABLE LUGAR (
	LUG_CODIGO SERIAL,
	LUG_NOMBRE VARCHAR(25) NOT NULL,
	LUG_TIPO VARCHAR(12) NOT NULL,
	FK_LUG_LUGAR INTEGER,
	CONSTRAINT PK_CODIGO_LUGAR PRIMARY KEY (LUG_CODIGO),
	CONSTRAINT CHECK_TIPO_LUGAR CHECK (LUG_TIPO IN ('ESTADO','PARROQUIA','MUNICIPIO')),
	CONSTRAINT FK_LUGAR_LUGAR FOREIGN KEY (FK_LUG_LUGAR) REFERENCES LUGAR (LUG_CODIGO)
);

CREATE TABLE CARGO (
	CAR_CODIGO SERIAL,
	CAR_NOMBRE VARCHAR (25) NOT NULL,
	CONSTRAINT PK_CODIGO_CARGO PRIMARY KEY (CAR_CODIGO)
);

CREATE TABLE ROL (
	ROL_CODIGO SERIAL,
	ROL_NOMBRE VARCHAR(10) NOT NULL,
	CONSTRAINT PK_CODIGO_ROL PRIMARY KEY (ROL_CODIGO),
	CONSTRAINT CHECK_ROL CHECK (ROL_NOMBRE IN ('ADMINISTRADOR','VENDEDOR','RH','ESPECIALISTA','GESTOR'))
);

CREATE TABLE PRIVILEGIO(
	PRI_CODIGO SERIAL,
	PRI_NOMBRE VARCHAR(15) NOT NULL,
	CONSTRAINT PK_CODIGO_PRIVILEGIO PRIMARY KEY (PRI_CODIGO)
);

CREATE TABLE PRESENTACION(
	PRE_CODIGO SERIAL,
	PRE_NOMBRE VARCHAR(15) NOT NULL,
	CONSTRAINT PK_CODIGO_PRESENTACION PRIMARY KEY (PRE_CODIGO)
);

CREATE TABLE EMPLEADO(
	EMP_ID SERIAL,
	EMP_CEDULA NUMERIC(8) NOT NULL UNIQUE,
	EMP_NOMBRE VARCHAR(15) NOT NULL,
	EMP_APELLIDO VARCHAR(15) NOT NULL,
	EMP_FECHANACIMIENTO DATE NOT NULL,
	EMP_GENERO CHAR(1) NOT NULL,
	EMP_TELEFONO NUMERIC(15) NOT NULL,
	FK_EMP_CARGO INTEGER NOT NULL,
	FK_EMP_LUGAR INTEGER NOT NULL,
	FK_EMP_ESTATUS INTEGER,
	CONSTRAINT PK_ID_EMPLEADO PRIMARY KEY (EMP_ID),
	CONSTRAINT CHECK_GENERO CHECK (EMP_GENERO IN ('M','F','O')),
	CONSTRAINT FK_CARGO_EMPLEADO FOREIGN KEY(FK_EMP_CARGO) REFERENCES CARGO (CAR_CODIGO),
	CONSTRAINT FK_LUGAR_EMPLEADO FOREIGN KEY(FK_EMP_LUGAR) REFERENCES LUGAR (LUG_CODIGO),
	CONSTRAINT FK_ESTATUS_EMPLEADO FOREIGN KEY(FK_EMP_ESTATUS) REFERENCES ESTATUS (EST_CODIGO)
);

CREATE TABLE USUARIO(
	USU_USUARIO SERIAL,
	USU_PASSWORD NUMERIC(8) NOT NULL,
	FK_USU_ESTATUS INTEGER NOT NULL,
	FK_USU_EMPLEADO_ID INTEGER NOT NULL,
	FK_USU_ROL INTEGER NOT NULL,
	CONSTRAINT PK_USUARIO_USUARIO PRIMARY KEY (USU_USUARIO),
	CONSTRAINT FK_ESTATUS_USUARIO FOREIGN KEY (FK_USU_ESTATUS) REFERENCES ESTATUS (EST_CODIGO),
	CONSTRAINT FK_ROL_USUARIO FOREIGN KEY (FK_USU_ROL) REFERENCES ROL (ROL_CODIGO),
	CONSTRAINT FK_EMPLEADO_ID_USUARIO FOREIGN KEY (FK_USU_EMPLEADO_ID) REFERENCES EMPLEADO (EMP_CEDULA)
);

CREATE TABLE ALIADO_COMERCIAL (
	AC_NUMERO_RIF VARCHAR(20) NOT NULL UNIQUE,
	AC_NOMBRE VARCHAR(15) NOT NULL,
	AC_TELEFONO NUMERIC(10) NOT NULL,
	FK_AC_LUGAR INTEGER NOT NULL,
	FK_AC_ESTATUS INTEGER NOT NULL,
	CONSTRAINT PK_NUMERO_RIF_ALIADO_COMERCIAL PRIMARY KEY(AC_NUMERO_RIF),
	CONSTRAINT FK_LUGAR_ALIADO_COMERCIAL FOREIGN KEY (FK_AC_LUGAR) REFERENCES LUGAR (LUG_CODIGO),
	CONSTRAINT FK_ESTATUS_ALIADO_COMERCIAL FOREIGN KEY (FK_AC_ESTATUS) REFERENCES ESTATUS (EST_CODIGO)
);

CREATE TABLE TIPO_MAQUINARIA(
	TM_CODIGO SERIAL, 
	TM_NOMBRE VARCHAR(15) NOT NULL,
	FK_TM_ESTATUS INTEGER NOT NULL,
	FK_TM_TIPO INTEGER NOT NULL,
	CONSTRAINT PK_CODIGO_TIPO_MAQUINARIA PRIMARY KEY (TM_CODIGO)
);

CREATE TABLE MAQUINARIA(
	MAQ_CODIGO SERIAL,
	MAQ_NOMBRE VARCHAR(15) NOT NULL,
	FK_MAQ_ESTATUS INTEGER NOT NULL,
	FK_MAQ_TIPO INTEGER NOT NULL,
	CONSTRAINT PK_CODIGO_MAQUINARIA PRIMARY KEY (MAQ_CODIGO),
	CONSTRAINT FK_ESTATUS_MAQUINARIA FOREIGN KEY (FK_MAQ_ESTATUS) REFERENCES ESTATUS(EST_CODIGO),
	CONSTRAINT FK_TIPO_MAQUINARIA FOREIGN KEY (FK_MAQ_TIPO) REFERENCES TIPO_MAQUINARIA(TM_CODIGO)
);

CREATE TABLE CLIENTE (
	CLI_CODIGO SERIAL,
	CLI_CEDULA NUMERIC(8) NOT NULL UNIQUE,
	CLI_NOMBRE VARCHAR(15) NOT NULL,
	CLI_APELLIDO VARCHAR(15) NOT NULL,
	CLI_TELEFONO NUMERIC(10) NOT NULL,
	FK_CLI_LUGAR INTEGER NOT NULL,
	CONSTRAINT PK_CODIGO_CLIENTE PRIMARY KEY (CLI_CODIGO),
	CONSTRAINT FK_LUGAR_CLIENTE FOREIGN KEY (FK_CLI_LUGAR) REFERENCES LUGAR(LUG_CODIGO)
);

CREATE TABLE VENTA(
	VEN_CODIGO SERIAL,
	VEN_FECHA DATE NOT NULL,
	VEN_MONTOTOTAL NUMERIC(15) NOT NULL,
	FK_VEN_CLIENTE INTEGER NOT NULL,
	FK_VEN_USUARIO INTEGER NOT NULL,
	CONSTRAINT PK_CODIGO_VENTA PRIMARY KEY (VEN_CODIGO),
	CONSTRAINT FK_CLIENTE_VENTA FOREIGN KEY (FK_VEN_CLIENTE) REFERENCES CLIENTE(CLI_CODIGO),
	CONSTRAINT FK_USUARIO_VENTA FOREIGN KEY (FK_VEN_USUARIO) REFERENCES USUARIO(USU_USUARIO),
	CONSTRAINT CHECK_MONTOTOTAL_VENTA CHECK (VEN_MONTOTOTAL > 0)
);

CREATE TABLE EXPLOTACION(
	EXP_CODIGO SERIAL,
	EXP_FECHAINICIO DATE NOT NULL,
	EXP_FECHAFIN DATE,
	EXP_COSTOTOTAL NUMERIC(15) NOT NULL,
	FK_EXP_ESTATUS INTEGER NOT NULL,
	FK_EXP_VENTA INTEGER,
	CONSTRAINT PK_CODIGO_EXPLOTACION PRIMARY KEY (EXP_CODIGO),
	CONSTRAINT FK_ESTATUS_EXPLOTACION FOREIGN KEY (FK_EXP_ESTATUS) REFERENCES ESTATUS(EST_CODIGO),
	CONSTRAINT FK_VENTA_EXPLOTACION FOREIGN KEY (FK_EXP_VENTA) REFERENCES VENTA(VEN_CODIGO),
	CONSTRAINT CHECK_COSTOTOTAL_EXPLOTACION CHECK (EXP_COSTOTOTAL > 0)
);

CREATE TABLE YACIMIENTO(
	YAC_CODIGO SERIAL,
	YAC_EXTENSION NUMERIC(15) NOT NULL,
	YAC_FECHAREGISTRO DATE NOT NULL,
	FK_YAC_ESTATUS INTEGER NOT NULL,
	FK_YAC_LUGAR INTEGER NOT NULL,
	FK_YAC_EXPLOTACION INTEGER,
	CONSTRAINT PF_CODIGO_YACIMIENTO PRIMARY KEY (YAC_CODIGO),
	CONSTRAINT FK_EXPLOTACION_YACIMIENTO FOREIGN KEY (FK_YAC_EXPLOTACION) REFERENCES EXPLOTACION(EXP_CODIGO),
	CONSTRAINT FK_ESTATUS_YACIMIENTO FOREIGN KEY (FK_YAC_ESTATUS) REFERENCES ESTATUS(EST_CODIGO),
	CONSTRAINT FK_LUGAR_YACIMIENTO FOREIGN KEY (FK_YAC_LUGAR) REFERENCES LUGAR(LUG_CODIGO)
);

CREATE TABLE ETAPA (
	ETA_CODIGO SERIAL,
	ETA_NOMBRE VARCHAR(15) NOT NULL,
	ETA_FECHAINICIO DATE NOT NULL,
	ETA_FECHAFIN DATE,
	ETA_COSTOTOTAL NUMERIC(15) NOT NULL,
	FK_ETA_EXPLOTACION INTEGER,
	FK_ETA_ESTATUS INTEGER NOT NULL,
	CONSTRAINT PK_CODIGO_ETAPA PRIMARY KEY (ETA_CODIGO),
	CONSTRAINT FK_ESTATUS_ETAPA FOREIGN KEY (FK_ETA_ESTATUS) REFERENCES ESTATUS (EST_CODIGO),
	CONSTRAINT FK_EXPLOTACION_ETAPA FOREIGN KEY (FK_ETA_EXPLOTACION) REFERENCES EXPLOTACION (EXP_CODIGO),
	CONSTRAINT CHECK_COSTOTOTAL_ETAPA CHECK (ETA_COSTOTOTAL > 0)
);

CREATE TABLE FASE(
	FAS_CODIGO SERIAL,
	FAS_NOMBRE VARCHAR(15) NOT NULL,
	FAS_FECHAINICIO DATE NOT NULL,
	FAS_FECHAFIN DATE,
	FAS_COSTOTOTAL NUMERIC(15) NOT NULL,
	FK_FAS_ETAPA INTEGER NOT NULL,
	FK_FAS_ESTATUS INTEGER NOT NULL,
	CONSTRAINT PK_CODIGO_FASE PRIMARY KEY (FAS_CODIGO),
	CONSTRAINT FK_ETAPA_FASE FOREIGN KEY (FK_FAS_ETAPA) REFERENCES ETAPA (ETA_CODIGO),
	CONSTRAINT FK_ESTATUS_FASE FOREIGN KEY (FK_FAS_ESTATUS) REFERENCES ESTATUS (EST_CODIGO),
	CONSTRAINT CHECK_COSTOTOTAL_FASE CHECK (FAS_COSTOTOTAL > 0)
);
